food_items = [
    {'name': 'Basmati Rice', 'category': 'Staples', 'protein': 7, 'carbs': 78, 'fiber': 1, 'calories': 350,
     'price': {'BigBasket': 45, 'Blinkit': 48, 'Amazon': 46, 'DMart': 43}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Toor Dal', 'category': 'Protein', 'protein': 22, 'carbs': 57, 'fiber': 15, 'calories': 340,
     'price': {'BigBasket': 85, 'Blinkit': 88, 'Amazon': 87, 'DMart': 82}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Paneer', 'category': 'Protein', 'protein': 18, 'carbs': 1.2, 'fiber': 0, 'calories': 265,
     'price': {'BigBasket': 280, 'Blinkit': 290, 'Amazon': 285, 'DMart': 275}, 'tags': ['vegetarian', 'non_vegan']},
    {'name': 'Spinach', 'category': 'Vegetables', 'protein': 2.9, 'carbs': 3.6, 'fiber': 2.2, 'calories': 25,
     'price': {'BigBasket': 20, 'Blinkit': 22, 'Amazon': 21, 'DMart': 18}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Bananas', 'category': 'Fruits', 'protein': 1.1, 'carbs': 23, 'fiber': 2.6, 'calories': 90,
     'price': {'BigBasket': 35, 'Blinkit': 38, 'Amazon': 36, 'DMart': 33}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Eggs', 'category': 'Protein', 'protein': 13, 'carbs': 1.1, 'fiber': 0, 'calories': 155,
     'price': {'BigBasket': 60, 'Blinkit': 65, 'Amazon': 62, 'DMart': 58}, 'tags': ['non_vegetarian']},
    {'name': 'Whole Wheat Flour', 'category': 'Staples', 'protein': 12, 'carbs': 71, 'fiber': 10.7, 'calories': 340,
     'price': {'BigBasket': 38, 'Blinkit': 40, 'Amazon': 39, 'DMart': 36}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Sunflower Oil', 'category': 'Cooking', 'protein': 0, 'carbs': 0, 'fiber': 0, 'calories': 884,
     'price': {'BigBasket': 140, 'Blinkit': 145, 'Amazon': 142, 'DMart': 138}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Onions', 'category': 'Vegetables', 'protein': 1.1, 'carbs': 9.3, 'fiber': 1.7, 'calories': 40,
     'price': {'BigBasket': 25, 'Blinkit': 28, 'Amazon': 26, 'DMart': 24}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Tomatoes', 'category': 'Vegetables', 'protein': 0.9, 'carbs': 3.9, 'fiber': 1.2, 'calories': 18,
     'price': {'BigBasket': 30, 'Blinkit': 32, 'Amazon': 31, 'DMart': 28}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Green Peas', 'category': 'Vegetables', 'protein': 5, 'carbs': 14, 'fiber': 5.1, 'calories': 81,
     'price': {'BigBasket': 45, 'Blinkit': 47, 'Amazon': 46, 'DMart': 42}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Apple', 'category': 'Fruits', 'protein': 0.3, 'carbs': 14, 'fiber': 2.4, 'calories': 52,
     'price': {'BigBasket': 90, 'Blinkit': 95, 'Amazon': 92, 'DMart': 88}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Ginger', 'category': 'Spices', 'protein': 1.8, 'carbs': 18, 'fiber': 2, 'calories': 80,
     'price': {'BigBasket': 120, 'Blinkit': 125, 'Amazon': 123, 'DMart': 118}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Garlic', 'category': 'Spices', 'protein': 6.4, 'carbs': 33, 'fiber': 2.1, 'calories': 149,
     'price': {'BigBasket': 110, 'Blinkit': 115, 'Amazon': 113, 'DMart': 110}, 'tags': ['vegetarian', 'vegan']},
    {'name': 'Milk (Toned)', 'category': 'Dairy', 'protein': 3.2, 'carbs': 4.5, 'fiber': 0, 'calories': 42,
     'price': {'BigBasket': 28, 'Blinkit': 30, 'Amazon': 29, 'DMart': 27}, 'tags': ['vegetarian', 'non_vegan']},
    {'name': 'Cumin Seeds', 'category': 'Spices', 'protein': 18, 'carbs': 44, 'fiber': 10.5, 'calories': 375,
     'price': {'BigBasket': 150, 'Blinkit': 155, 'Amazon': 152, 'DMart': 148}, 'tags': ['vegetarian', 'vegan']},
]
